# -*- coding: utf-8 -*-
"""Build the neural transliterator's training data from free, human-authored
sources (see ``data/SOURCES.md``):

* Wiktionary Urdu (kaikki.org dump)   -- Urdu word + inflections + roman (+ Hindi spelling)
* Wiktionary Hindi (kaikki.org dump)  -- Hindi word + inflections + roman; Urdu spelling
  either given by the entry or generated by ``deva_to_urdu_candidates`` and kept
  only when a real Urdu corpus attests it
* Aksharantar Urdu (AI4Bharat)        -- 700k Urdu word -> casual roman pairs
* Dakshina Urdu (Google Research)     -- romanisation lexicon + 10k word-aligned
  romanised sentences; its Wikipedia text is the attestation corpus

Outputs (``data/translit_ds/``):

  train.tsv / dev.tsv   task \\t src \\t tgt \\t weight
                        task j: urdu -> "R|devanagari"   (both known; Devanagari
                                conditioned on the Roman reading, so they agree)
                        task r: urdu -> R                (Devanagari unknown)
                        task c: urdu -> casual roman     (Aksharantar / Dakshina)
                        task h: R -> devanagari          (Hindi Wiktionary, 85k:
                                Hindi orthography for readings the lexicon has
                                no Devanagari for)
  test.jsonl            held-out gold words {urdu, R, deva, src}
  lexicon_train.json    gold lexicon without the test words (for honest eval)
  lexicon_full.json     gold lexicon over everything (what ships)
  evidence_*.json.gz    urdu -> {casual roman: weight} (top 3) from Aksharantar/Dakshina
                        (runtime beam reranking; _train omits held-out words)
  stats.json

Run:  python -m training.translit.build_data
"""
from __future__ import annotations

import argparse
import collections
import gzip
import hashlib
import json
import random
import re
import unicodedata
import zipfile
from pathlib import Path

import difflib

from urdu_nn.scheme import (
    deva_to_urdu_candidates, fold_roman, is_urdu_word, norm_urdu, to_plain, wik_to_rich,
)

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "data" / "translit_raw"
OUT = ROOT / "data" / "translit_ds"
DAK = RAW / "dakshina_dataset_v1.0" / "ur"

_DEVA = re.compile(r"^[ऀ-ॿ]+$")
_CASUAL = re.compile(r"^[a-z]+$")


def _isur(s: str) -> bool:
    return any("؀" <= c <= "ۿ" for c in s)


def _bucket(key: str) -> float:
    return int(hashlib.md5(key.encode("utf-8")).hexdigest()[:8], 16) / 0xFFFFFFFF


# ---------------------------------------------------------------------------
# attestation corpus
# ---------------------------------------------------------------------------

def attested_counts() -> collections.Counter:
    cnt: collections.Counter = collections.Counter()
    tok = re.compile(r"[؀-ۿٰٔ]+")
    for name in ("ur.wiki-filt.train.text.shuf.txt.gz", "ur.wiki-filt.valid.text.shuf.txt.gz"):
        p = DAK / "native_script_wikipedia" / name
        if not p.exists():
            continue
        with gzip.open(p, "rt", encoding="utf-8") as fh:
            for line in fh:
                for w in tok.findall(line):
                    cnt[norm_urdu(w)] += 1
    for p in (ROOT / "training" / "corpus").glob("*.txt"):
        for line in p.read_text(encoding="utf-8").splitlines():
            for w in tok.findall(line):
                cnt[norm_urdu(w)] += 1
    return cnt


# ---------------------------------------------------------------------------
# Wiktionary
# ---------------------------------------------------------------------------

def _pairs_from_phrase(urdu: str, roman: str):
    """Split a multi-word (urdu, roman) into word pairs when counts line up."""
    us = urdu.split()
    rs = re.split(r"[ \-]", roman)
    rs = [r for r in rs if r]
    if len(us) == len(rs):
        return list(zip(us, rs))
    if len(us) == 1:
        return [(urdu, roman.replace("-", ""))]
    return []


def hindi_roman_map():
    """R (from Hindi Wiktionary romanisation) -> Devanagari, most frequent."""
    r2d: dict[str, collections.Counter] = {}
    with open(RAW / "kaikki_hi.jsonl", encoding="utf-8") as fh:
        for line in fh:
            e = json.loads(line)
            items = []
            for f in e.get("forms", []):
                form = f.get("form", "")
                if f.get("roman") and _DEVA.match(form):
                    items.append((form, f["roman"], 1))
                if "romanization" in f.get("tags", []) and _DEVA.match(e["word"]):
                    items.append((e["word"], form, 5))   # headword beats table cells
            for deva, rom, w in items:
                rich = wik_to_rich(rom, source="hi")
                if rich and " " not in rich:
                    r2d.setdefault(rich, collections.Counter())[unicodedata.normalize("NFC", deva)] += w
    return {r: c.most_common(1)[0][0] for r, c in r2d.items()}


def urdu_wiktionary(r2d):
    """Yield dict(urdu, voc, rich, deva, lemma, kind)."""
    with open(RAW / "kaikki_ur.jsonl", encoding="utf-8") as fh:
        for line in fh:
            e = json.loads(line)
            word = e.get("word", "")
            if not _isur(word):
                continue
            lemma = "ur:" + norm_urdu(word)
            forms = e.get("forms", [])
            rom = next((f["form"] for f in forms if "romanization" in f.get("tags", [])), None)
            hi = next((f["form"] for f in forms if "Hindi" in f.get("tags", [])
                       and _DEVA.match(f.get("form", ""))), None)
            canon = next((f["form"] for f in forms if "canonical" in f.get("tags", [])
                          and _isur(f.get("form", ""))), word)
            if rom:
                for u, r in _pairs_from_phrase(canon, rom):
                    rich = wik_to_rich(r, u, "ur")
                    if rich and " " not in rich and is_urdu_word(norm_urdu(u, keep_harakat=True)):
                        deva = hi if (hi and " " not in canon and " " not in rom) else r2d.get(rich)
                        yield dict(urdu=norm_urdu(u), voc=norm_urdu(u, True), rich=rich,
                                   deva=deva, lemma=lemma, kind="lemma")
            for f in forms:
                form, r = f.get("form", ""), f.get("roman")
                if not r or not _isur(form) or "،" in form or "," in r:
                    continue
                for u, rr in _pairs_from_phrase(form, r):
                    rich = wik_to_rich(rr, u, "ur")
                    if rich and " " not in rich and is_urdu_word(norm_urdu(u, keep_harakat=True)):
                        yield dict(urdu=norm_urdu(u), voc=norm_urdu(u, True), rich=rich,
                                   deva=r2d.get(rich), lemma=lemma, kind="form")
            for s in e.get("senses", []):
                for x in s.get("examples", []):
                    t, r = x.get("text", ""), x.get("roman", "")
                    if not (_isur(t) and r):
                        continue
                    t = re.sub(r"[۔،؟!?.,:;\"'«»()]", " ", t)
                    r = re.sub(r"[?!.,:;\"«»()]", " ", r)
                    for u, rr in _pairs_from_phrase(" ".join(t.split()), " ".join(r.split())):
                        rich = wik_to_rich(rr, u, "ur")
                        if rich and is_urdu_word(norm_urdu(u, keep_harakat=True)):
                            yield dict(urdu=norm_urdu(u), voc=norm_urdu(u, True), rich=rich,
                                       deva=r2d.get(rich), lemma=lemma, kind="example")


def _stem(urdu: str) -> str:
    for suf in ("نا", "ا", "ہ", "ی", "ے", "ں"):
        if urdu.endswith(suf) and len(urdu) - len(suf) >= 2:
            return urdu[: -len(suf)]
    return urdu


def hindi_wiktionary(att: collections.Counter, min_att: int, known: set[str]):
    """Yield dict(urdu, voc, rich, deva, lemma, kind) from Hindi entries."""
    with open(RAW / "kaikki_hi.jsonl", encoding="utf-8") as fh:
        for line in fh:
            e = json.loads(line)
            word = unicodedata.normalize("NFC", e.get("word", ""))
            if not _DEVA.match(word):
                continue
            forms = e.get("forms", [])
            rom = next((f["form"] for f in forms if "romanization" in f.get("tags", [])), None)
            ur = next((f["form"] for f in forms if "Urdu" in f.get("tags", [])
                       and _isur(f.get("form", "")) and " " not in f["form"].strip()), None)
            lemma = "hi:" + word
            items = []
            if rom:
                items.append((word, rom, "lemma"))
            for f in forms:
                form = unicodedata.normalize("NFC", f.get("form", ""))
                if f.get("roman") and _DEVA.match(form) and form != word:
                    items.append((form, f["roman"], "form"))
            ur_n = norm_urdu(ur) if ur else None
            stem = _stem(ur_n) if ur_n else None
            seen = set()
            for deva, r, kind in items:
                if deva in seen:
                    continue
                seen.add(deva)
                rich = wik_to_rich(r, source="hi")
                if not rich or " " in rich:
                    continue
                if kind == "lemma" and ur_n:
                    yield dict(urdu=ur_n, voc=norm_urdu(ur, True), rich=rich, deva=deva,
                               lemma=lemma, kind="hi-lemma-ur")
                    continue
                cands = deva_to_urdu_candidates(deva)
                if not cands:
                    continue
                if stem:
                    on_stem = [c for c in cands if c.startswith(stem)]
                    best = max(on_stem, key=lambda c: att.get(c, 0)) if on_stem else None
                    if best and att.get(best, 0) >= 1:
                        yield dict(urdu=best, voc=best, rich=rich, deva=deva,
                                   lemma=lemma, kind="hi-form-ur")
                    continue
                best = max(cands, key=lambda c: att.get(c, 0))
                # a generated spelling that collides with a real Urdu headword
                # is far more likely that word than this Hindi one (دیو = dev)
                if att.get(best, 0) >= min_att and len(best) >= 3 and best not in known:
                    yield dict(urdu=best, voc=best, rich=rich, deva=deva,
                               lemma=lemma, kind="hi-attested")


# ---------------------------------------------------------------------------
# casual romanisation sources
# ---------------------------------------------------------------------------

def aksharantar():
    z = zipfile.ZipFile(RAW / "aksharantar_urd.zip")
    for name in ("urd_train.json", "urd_valid.json", "urd_test.json"):
        for line in z.read(name).decode("utf-8").splitlines():
            x = json.loads(line)
            u, r = norm_urdu(x["native word"]), x["english word"].strip().lower()
            if x.get("source") == "IndicCorp" and (x.get("score") or 0) < -0.3:
                continue
            if is_urdu_word(u) and _CASUAL.match(r):
                yield u, r, x.get("source", "")


def dakshina_lexicon():
    for split in ("train", "dev", "test"):
        p = DAK / "lexicons" / f"ur.translit.sampled.{split}.tsv"
        best: dict[str, tuple[int, str]] = {}
        for line in p.read_text(encoding="utf-8").splitlines():
            u, r, c = line.split("\t")
            u, r = norm_urdu(u), r.lower()
            if is_urdu_word(u) and _CASUAL.match(r) and int(c) > best.get(u, (0, ""))[0]:
                best[u] = (int(c), r)
        for u, (_, r) in best.items():
            yield u, r


def dakshina_sentences(skip_native: set[str]):
    """Word-aligned romanised sentences, skipping the ones held out for eval."""
    natives = [l.split("\t")[0] for l in
               (DAK / "romanized" / "ur.romanized.rejoined.tsv").read_text(encoding="utf-8").splitlines()]
    sent, idx = [], 0
    for line in (DAK / "romanized" / "ur.romanized.rejoined.aligned.cased_nopunct.tsv") \
            .read_text(encoding="utf-8").splitlines():
        if line.startswith("</s>"):
            if idx < len(natives) and natives[idx] not in skip_native:
                yield sent
            sent, idx = [], idx + 1
            continue
        parts = line.split("\t")
        if len(parts) == 2:
            u, r = norm_urdu(parts[0]), parts[1].lower()
            if " " not in u and is_urdu_word(u) and _CASUAL.match(r):
                sent.append((u, r))


# ---------------------------------------------------------------------------
# English loanwords & proper names: casual Roman uses the English spelling
# (school, station, London) even though the reading is phonetic (skūl)
# ---------------------------------------------------------------------------

_BORROWED = re.compile(r"(?:borrowing|[Bb]orrowed|[Dd]erived|[Ff]rom) from English ([A-Za-z][A-Za-z\-]+)"
                       r"|^From English ([A-Za-z][A-Za-z\-]+)")


def english_layer(votes, casual_rows) -> dict[str, str]:
    """urdu -> English spelling, from (a) Wiktionary "borrowed from English X",
    (b) Wiktionary proper-noun glosses that SOUND like the Urdu word (keeps
    London, drops Egypt for مصر = Misr), (c) Aksharantar/Dakshina casual
    romanisations that are English words (English vocabulary = every word in
    Wiktionary's English glosses) and dominate that spelling's evidence."""
    out: dict[str, str] = {}
    names: dict[str, str] = {}
    borrowed: dict[str, str] = {}
    vocab: set[str] = set()
    native: set[str] = set()

    def sounds_like(eng_word, u):
        if u not in votes:
            return False
        rich = votes[u].most_common(1)[0][0]
        a, b = fold_roman(eng_word), fold_roman(to_plain(rich))
        return difflib.SequenceMatcher(None, a, b).ratio() >= 0.5

    for path in (RAW / "kaikki_ur.jsonl", RAW / "kaikki_hi.jsonl"):
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                e = json.loads(line)
                for sense in e.get("senses", []):
                    for g in sense.get("glosses", []):
                        vocab.update(w.lower() for w in re.findall(r"[A-Za-z]{3,}", g))
                if path.name != "kaikki_ur.jsonl" or not _isur(e.get("word", "")):
                    continue
                u = norm_urdu(e["word"])
                if " " in u:
                    continue
                m = _BORROWED.search(e.get("etymology_text", "") or "")
                if m:
                    borrowed[u] = (m.group(1) or m.group(2)).lower()
                    continue
                if e.get("pos") != "name":
                    native.add(u)
                    continue
                for sense in e.get("senses", [])[:1]:
                    g = (sense.get("glosses") or [""])[0]
                    name = re.split(r"[(,;:]", g)[0].strip()
                    arabic_gloss = re.search("th|dh", name.lower()) and not re.search(
                        "th|dh", to_plain(votes[u].most_common(1)[0][0]) if u in votes else "")
                    if (re.fullmatch(r"[A-Z][A-Za-z\-]+", name) and sounds_like(name, u)
                            and not arabic_gloss):
                        names[u] = name.lower()
    # a spelling that is also an ordinary Urdu word keeps its ordinary reading:
    # کار = kaar (work) not car, کالی = kaali not Kali
    out.update({u: n for u, n in borrowed.items() if u not in native})
    out.update({u: n for u, n in names.items() if u not in native and u not in out})
    raw: dict[str, collections.Counter] = {}
    for u, r, w in casual_rows:
        raw.setdefault(u, collections.Counter())[r] += w
    for u, c in raw.items():
        if u in out or u in native or u in votes:   # gold readings win (کار = kaar, not car)
            continue
        top, w = c.most_common(1)[0]
        if len(top) >= 5 and top in vocab and w / sum(c.values()) >= 0.6 and w >= 3:
            out[u] = top
    for u in ENGLISH_NOT:
        out.pop(u, None)
    out.update(ENGLISH_FIX)
    return out


# Hand review of the English layer: spellings that are ordinary Urdu words
# (کافی kaafi "enough", not coffee; چلی chali, not Chile; کیف kaif, جگ jag,
# لیل lail) or whose Urdu name isn't the English one (اردن urdun, رمضان ramzan)
# keep their phonetic reading.
ENGLISH_NOT = set(
    "ہند ہندوستان عربی ہسپانیہ اطالیہ المانیہ ولندیز برطانیہ انگلستان روس آئرستان "
    "ارمنستان متھن ابراہیم جبرائیل میکائیل یشوع ہوسیع ہوشیع یہوداہ تورات گنگا فرات "
    "قاہرہ اسکندریہ صقلیہ انطاکیہ رام کشن گنیش شیو بور پال کیلے لیل لیون سلینڈر سلاپ "
    "وندر کبل شکی مرو کولن گلیل کملا پتلون بوچڑ اردلی ماچس بکس جگ درجن افسر کافی کوفی "
    "کیف عمان ارسطو رمضان گنی چلی فٹ نیٹرون انترم ٹماٹر اردن فلسطین دمشق ہندومت "
    "مورمنیت غرناطہ کنعان".split())
ENGLISH_FIX = {
    "کیفے": "cafe", "نوبل": "nobel", "پوپ": "pope", "سلیمان": "sulaiman",
    "مہابھارت": "mahabharat", "رامائن": "ramayan", "مہایان": "mahayan", "رگوید": "rigved",
    "دریودھن": "duryodhan", "ہمالیہ": "himalaya", "چیت": "chait",
}


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--min-att", type=int, default=3,
                    help="corpus count needed to accept a generated Urdu spelling")
    ap.add_argument("--test-frac", type=float, default=0.04)
    ap.add_argument("--dev-frac", type=float, default=0.02)
    args = ap.parse_args(argv)
    OUT.mkdir(parents=True, exist_ok=True)
    rng = random.Random(7)

    print("attestation corpus ...", flush=True)
    att = attested_counts()
    print(f"  {len(att)} distinct Urdu tokens", flush=True)
    print("hindi roman->deva map ...", flush=True)
    r2d = hindi_roman_map()
    print(f"  {len(r2d)} keys", flush=True)

    gold = list(urdu_wiktionary(r2d))
    print(f"urdu wiktionary: {len(gold)} rows", flush=True)
    hi = list(hindi_wiktionary(att, args.min_att, {g["urdu"] for g in gold}))
    print(f"hindi wiktionary: {len(hi)} rows "
          f"{collections.Counter(h['kind'] for h in hi)}", flush=True)

    # --- split by lemma (test / dev / train) -----------------------------
    def split_of(lemma):
        b = _bucket(lemma)
        return "test" if b < args.test_frac else ("dev" if b < args.test_frac + args.dev_frac else "train")

    rows = gold + hi
    held_keys = {"test": set(), "dev": set()}
    for x in rows:
        s = split_of(x["lemma"])
        if s != "train" and x["kind"] in ("lemma", "form", "hi-lemma-ur", "hi-form-ur"):
            held_keys[s].add(x["urdu"])
    # a word that is held out anywhere is held out everywhere
    held_keys["dev"] -= held_keys["test"]
    held_all = held_keys["test"] | held_keys["dev"]

    # --- gold lexicon: urdu -> reading votes -------------------------------
    trust = {"lemma": 3, "hi-lemma-ur": 3, "form": 2, "hi-form-ur": 1, "example": 2, "hi-attested": 0}
    votes: dict[str, collections.Counter] = {}
    deva_votes: dict[tuple[str, str], collections.Counter] = {}
    for x in rows:
        # word-final silent he is a short a (sabza, parda), whatever the source wrote
        if x["urdu"].endswith("ہ") and x["rich"].endswith("ā"):
            x["rich"] = x["rich"][:-1] + "a"
    for x in rows:
        if trust[x["kind"]] == 0:
            continue
        votes.setdefault(x["urdu"], collections.Counter())[x["rich"]] += trust[x["kind"]]
        if x["deva"]:
            deva_votes.setdefault((x["urdu"], x["rich"]), collections.Counter())[x["deva"]] += 1

    # casual romanisations (how people actually read each spelling) break ties
    # between homograph readings: چھوٹا -> choṭā (small) over chūṭā (left behind)
    test_sent = set((DAK / "romanized" / "ur.romanized.rejoined.test.native.txt")
                    .read_text(encoding="utf-8").splitlines())
    casual_rows = [(u, r, 1.0 if src in ("Dakshina", "Existing", "AK-Uni") else 0.5)
                   for u, r, src in aksharantar()]
    casual_rows += [(u, r, 1.0) for u, r in dakshina_lexicon()]
    casual_rows += [(u, r, 0.5) for sent in dakshina_sentences(test_sent) for u, r in sent]
    evidence: dict[str, collections.Counter] = {}
    for u, r, w in casual_rows:
        if u in votes and len(votes[u]) > 1:
            evidence.setdefault(u, collections.Counter())[fold_roman(r)] += w

    def pick_reading(u):
        cands = votes[u]
        if len(cands) == 1 or u not in evidence:
            return cands.most_common(1)[0][0]
        ev = evidence[u]

        def score(rich):
            f = fold_roman(to_plain(rich))
            return sum(c * difflib.SequenceMatcher(None, f, e).ratio() ** 4 for e, c in ev.items())
        return max(cands, key=lambda r: (score(r), cands[r]))

    def lex_entry(u):
        rich = pick_reading(u)
        if rich in r2d:            # Hindi Wiktionary's own spelling of exactly this reading
            return [r2d[rich], rich]
        dv = deva_votes.get((u, rich))
        return [dv.most_common(1)[0][0] if dv else None, rich]

    lex_full = {u: lex_entry(u) for u in votes}
    lex_train = {u: v for u, v in lex_full.items() if u not in held_all}
    (OUT / "lexicon_full.json").write_text(json.dumps(lex_full, ensure_ascii=False), encoding="utf-8")
    (OUT / "lexicon_train.json").write_text(json.dumps(lex_train, ensure_ascii=False), encoding="utf-8")

    # --- held-out test words (gold, one reading per word) ------------------
    test = []
    for u in sorted(held_keys["test"]):
        if u in votes:
            d, r = lex_entry(u)
            test.append({"urdu": u, "rich": r, "deva": d})
    rng.shuffle(test)
    with open(OUT / "test.jsonl", "w", encoding="utf-8") as fh:
        for t in test:
            fh.write(json.dumps(t, ensure_ascii=False) + "\n")

    # --- training samples ----------------------------------------------------
    samples = {"train": collections.Counter(), "dev": collections.Counter()}

    def add(split, task, src, tgt, w=1.0):
        if src and tgt and len(src) <= 40 and len(tgt) <= 60:
            samples[split][(task, src, tgt)] += w

    for x in rows:
        u = x["urdu"]
        if u in held_keys["test"]:
            continue
        split = "dev" if u in held_keys["dev"] else "train"
        w = {"lemma": 2.0, "hi-lemma-ur": 2.0, "form": 1.0, "hi-form-ur": 1.0,
             "example": 1.0, "hi-attested": 0.7}[x["kind"]]
        if x["deva"]:
            add(split, "j", u, f"{x['rich']}|{x['deva']}", w)
            if x["voc"] != u:   # harakat-bearing input: model should use them when present
                add(split, "j", x["voc"], f"{x['rich']}|{x['deva']}", 0.5 * w)
        else:
            add(split, "r", u, x["rich"], w)
            if x["voc"] != u:
                add(split, "r", x["voc"], x["rich"], 0.5 * w)

    for rich, deva in r2d.items():
        add("dev" if _bucket(rich) < 0.01 else "train", "h", rich, deva, 0.5)

    n_c = 0
    for u, r, w in casual_rows:
        if u in held_all:
            continue
        add("dev" if _bucket(u) < 0.01 else "train", "c", u, r, w)
        n_c += 1

    # casual evidence lexicon: how people actually romanise each spelling
    # (runtime reranks the model's beam with it). *_train drops held-out words.
    ev_all: dict[str, collections.Counter] = {}
    for u, r, w in casual_rows:
        ev_all.setdefault(u, collections.Counter())[r] += w
    # keep human-sourced / repeated entries, or spellings the Urdu corpus uses
    # (drops IndicCorp's one-off run-together junk and keeps runtime memory small)
    ev_json = {u: {f: round(w, 1) for f, w in c.most_common(3)} for u, c in ev_all.items()
               if sum(c.values()) >= 1.0 or att.get(u, 0) >= 3}
    for name, keep in (("evidence_full.json.gz", lambda u: True),
                       ("evidence_train.json.gz", lambda u: u not in held_all)):
        with gzip.open(OUT / name, "wt", encoding="utf-8") as fh:
            json.dump({u: v for u, v in ev_json.items() if keep(u)}, fh, ensure_ascii=False,
                      separators=(",", ":"))

    eng = english_layer(votes, casual_rows)
    for name, keep in (("english_full.json", lambda u: True),
                       ("english_train.json", lambda u: u not in held_all)):
        (OUT / name).write_text(json.dumps({u: v for u, v in eng.items() if keep(u)},
                                           ensure_ascii=False, indent=0), encoding="utf-8")

    stats = {"attested_tokens": len(att), "evidence_words": len(ev_json),
             "english_words": len(eng), "r2d": len(r2d), "urdu_wikt_rows": len(gold),
             "hindi_wikt_rows": len(hi), "casual_rows": n_c,
             "lexicon_full": len(lex_full), "lexicon_train": len(lex_train), "test_words": len(test)}
    for split, c in samples.items():
        with open(OUT / f"{split}.tsv", "w", encoding="utf-8") as fh:
            for (task, src, tgt), w in c.items():
                fh.write(f"{task}\t{src}\t{tgt}\t{min(w, 4.0):.2f}\n")
        stats[f"{split}_samples"] = dict(collections.Counter(t for t, _, _ in c))
    (OUT / "stats.json").write_text(json.dumps(stats, indent=1), encoding="utf-8")
    print(json.dumps(stats, indent=1))


if __name__ == "__main__":
    main()
